//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disbott.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Disbott.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Summoner -- Links the specified summoner to your discord account // **disbott setsummoner [summoner name]**.
        /// </summary>
        internal static string Comand_Lol_SetSummoner {
            get {
                return ResourceManager.GetString("Comand_Lol_SetSummoner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip -- Flips a coin! // **disbott flip**.
        /// </summary>
        internal static string Command_CoinFlip_Flip {
            get {
                return ResourceManager.GetString("Command_CoinFlip_Flip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giphy -- Gets a random gif // **disbott giphy [subject]**.
        /// </summary>
        internal static string Command_Giphy_Flip {
            get {
                return ResourceManager.GetString("Command_Giphy_Flip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Game -- Gets the current game for yourself or another discord/league account // **disbott currentgame [summoner name]**.
        /// </summary>
        internal static string Command_Lol_CurrentGame {
            get {
                return ResourceManager.GetString("Command_Lol_CurrentGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked Info -- Gets the ranked stats for yourself or another discord/league account // **disbott ranked [summoner name]**.
        /// </summary>
        internal static string Command_Lol_Ranked {
            get {
                return ResourceManager.GetString("Command_Lol_Ranked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Count -- Displays Current Message Count for Current or Another Discord User // **disbott messagecount**.
        /// </summary>
        internal static string Command_Message_Count_Count {
            get {
                return ResourceManager.GetString("Command_Message_Count_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Polls -- Gets all the current polls // **disbott currentpolls**.
        /// </summary>
        internal static string Command_Poll_Current {
            get {
                return ResourceManager.GetString("Command_Poll_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Poll -- Deletes a poll // **disbott deletepoll [Poll ID]**.
        /// </summary>
        internal static string Command_Poll_Delete {
            get {
                return ResourceManager.GetString("Command_Poll_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all Polls (Admin Only) -- Deletes all polls // **disbott deleteallpolls**.
        /// </summary>
        internal static string Command_Poll_DeleteAll {
            get {
                return ResourceManager.GetString("Command_Poll_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Poll -- Starts a new Poll // **disbott newpoll [Date Time] [Poll Title]**.
        /// </summary>
        internal static string Command_Poll_NewPoll {
            get {
                return ResourceManager.GetString("Command_Poll_NewPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote Poll -- Votes on a poll // **disbott votepoll [Poll ID] [yes/no]**.
        /// </summary>
        internal static string Command_Poll_VotePoll {
            get {
                return ResourceManager.GetString("Command_Poll_VotePoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Quote -- Removes quote from a person // **disbott deletequote [Quote]**.
        /// </summary>
        internal static string Command_Quote_Delete {
            get {
                return ResourceManager.GetString("Command_Quote_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote -- Randomly quotes a user // **disbott quote [username]**.
        /// </summary>
        internal static string Command_Quote_Quote {
            get {
                return ResourceManager.GetString("Command_Quote_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Quote -- Adds a new quote // **disbott addquote [Username] [Quote]**.
        /// </summary>
        internal static string Command_Quotes_AddQuote {
            get {
                return ResourceManager.GetString("Command_Quotes_AddQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Delete Reminder (Admin Only)-- Deletes a Reminder  // **disbott admindeletereminder [Poll ID]**.
        /// </summary>
        internal static string Command_Remindme_AdDeleteReminder {
            get {
                return ResourceManager.GetString("Command_Remindme_AdDeleteReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Reminders (Admin Only) -- Show all the current reminders // **disbott allreminders**.
        /// </summary>
        internal static string Command_Remindme_AllReminders {
            get {
                return ResourceManager.GetString("Command_Remindme_AllReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Reminder -- Deletes one of your current reminders // **disbott deletereminder [Poll ID]**.
        /// </summary>
        internal static string Command_Remindme_DeleteReminder {
            get {
                return ResourceManager.GetString("Command_Remindme_DeleteReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Reminders -- Show your current reminders // **disbott myreminders**.
        /// </summary>
        internal static string Command_Remindme_MyReminders {
            get {
                return ResourceManager.GetString("Command_Remindme_MyReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind Me In -- Reminds a user something in a set amount of time // **disbott remindmein [h] [m] [s] [Reminder]**.
        /// </summary>
        internal static string Command_Remindme_RemindIn {
            get {
                return ResourceManager.GetString("Command_Remindme_RemindIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind All In (Admin Only) -- Reminds all users something in a set amount of time // **disbott remindallin [h] [m] [s] [Reminder]**.
        /// </summary>
        internal static string Command_Remindme_RemindInAll {
            get {
                return ResourceManager.GetString("Command_Remindme_RemindInAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind Me Then -- Reminds a user something at a set time // **disbott remindmethen [Date/Time] [Reminder]**.
        /// </summary>
        internal static string Command_Remindme_RemindThen {
            get {
                return ResourceManager.GetString("Command_Remindme_RemindThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind All Then (Admin Only) --  Reminds all users something at a set time // **disbott remindallthen [Date/Time] [Reminder]**.
        /// </summary>
        internal static string Command_Remindme_RemindThenAll {
            get {
                return ResourceManager.GetString("Command_Remindme_RemindThenAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll Dice -- Rolls a dice // **disbott roll [xdy](Where x is number and y is sides)**.
        /// </summary>
        internal static string Command_Roll_Roll {
            get {
                return ResourceManager.GetString("Command_Roll_Roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gazo Tweet -- NSFW, gets a random image from the last 40 tweets on @idol_gazo twitter account // **disbott gazo**.
        /// </summary>
        internal static string Command_Twitter_gazo {
            get {
                return ResourceManager.GetString("Command_Twitter_gazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Headline -- Gets the latest tweet from The Guardian&apos;s Twitter Account // **disbott headline**.
        /// </summary>
        internal static string Command_Twitter_Headline {
            get {
                return ResourceManager.GetString("Command_Twitter_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Random Tweet -- Gets a random tweet in the last 40 for a user // **disbott randomtweet [Twitter name]**.
        /// </summary>
        internal static string Command_Twitter_RandomTweet {
            get {
                return ResourceManager.GetString("Command_Twitter_RandomTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Tweet -- Gets the last tweet from a user // **disbott tweet [Twitter Name]**.
        /// </summary>
        internal static string Command_Twitter_Tweet {
            get {
                return ResourceManager.GetString("Command_Twitter_Tweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About -- Tells the user about Disbott and its creators // **disbott about**.
        /// </summary>
        internal static string Command_Utils_About {
            get {
                return ResourceManager.GetString("Command_Utils_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help -- Gives explanation for all disbott commands // **disbott help [Module Name]**.
        /// </summary>
        internal static string Command_Utils_Help {
            get {
                return ResourceManager.GetString("Command_Utils_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info -- Tells user the current Disbott info // **disbott info**.
        /// </summary>
        internal static string Command_Utils_Info {
            get {
                return ResourceManager.GetString("Command_Utils_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill (Admin Only)-- Ruthlessly murders disbott // **disbott kill**.
        /// </summary>
        internal static string Command_Utils_Kill {
            get {
                return ResourceManager.GetString("Command_Utils_Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules -- Lists all the current disbott modules // **disbott modules**.
        /// </summary>
        internal static string Command_Utils_Modules {
            get {
                return ResourceManager.GetString("Command_Utils_Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping -- Checks disbott is alive // **disbott ping**.
        /// </summary>
        internal static string Command_Utils_Ping {
            get {
                return ResourceManager.GetString("Command_Utils_Ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **coinflip:** commands to flip a coin.
        /// </summary>
        internal static string Desc_Coinflip {
            get {
                return ResourceManager.GetString("Desc_Coinflip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **giphy:** commands to get Gifs from giphy.
        /// </summary>
        internal static string Desc_Giphy {
            get {
                return ResourceManager.GetString("Desc_Giphy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **leagueoflegends:** commands to get information about League of Legends accounts.
        /// </summary>
        internal static string Desc_Lol {
            get {
                return ResourceManager.GetString("Desc_Lol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **messagecount:** commands to get message count on a user.
        /// </summary>
        internal static string Desc_Message_Count {
            get {
                return ResourceManager.GetString("Desc_Message_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **polls:** commands to run a poll.
        /// </summary>
        internal static string Desc_Poll {
            get {
                return ResourceManager.GetString("Desc_Poll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **quotes:** commands to add quotes for a user.
        /// </summary>
        internal static string Desc_Quotes {
            get {
                return ResourceManager.GetString("Desc_Quotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **reminders:** commands to set timed reminders.
        /// </summary>
        internal static string Desc_Remind_Me {
            get {
                return ResourceManager.GetString("Desc_Remind_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **diceroll:** commands to roll a dice.
        /// </summary>
        internal static string Desc_Roll {
            get {
                return ResourceManager.GetString("Desc_Roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **twitter:** commands to get tweets from accounts.
        /// </summary>
        internal static string Desc_Twitter {
            get {
                return ResourceManager.GetString("Desc_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **utils:** commands to deal with utilities on disbott.
        /// </summary>
        internal static string Desc_Utils {
            get {
                return ResourceManager.GetString("Desc_Utils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add quote.
        /// </summary>
        internal static string error_Cant_Add_Quote {
            get {
                return ResourceManager.GetString("error_Cant_Add_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete quote.
        /// </summary>
        internal static string error_Could_Not_Delete {
            get {
                return ResourceManager.GetString("error_Could_Not_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input. Roll a dice by using the format &apos;xdy&apos;.
        /// </summary>
        internal static string error_Incorrect_Format_Dice {
            get {
                return ResourceManager.GetString("error_Incorrect_Format_Dice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type &apos;yes&apos; or &apos;no&apos;.
        /// </summary>
        internal static string error_Incorrect_Format_Poll {
            get {
                return ResourceManager.GetString("error_Incorrect_Format_Poll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow, this user has posted no messages, incredible lurking.
        /// </summary>
        internal static string error_No_Messages {
            get {
                return ResourceManager.GetString("error_No_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grats you rolled a d1, hope you are proud.
        /// </summary>
        internal static string error_OneSide_Dice {
            get {
                return ResourceManager.GetString("error_OneSide_Dice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To avoid spam you cannot roll more than 100 dice or a d100 (Sorry).
        /// </summary>
        internal static string error_Too_Many_Dice {
            get {
                return ResourceManager.GetString("error_Too_Many_Dice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has no quotes.
        /// </summary>
        internal static string error_User_No_Quotes {
            get {
                return ResourceManager.GetString("error_User_No_Quotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I\&apos;m Disbott. A bot for Discord. Find out more about me here {0}.
        /// </summary>
        internal static string response_About {
            get {
                return ResourceManager.GetString("response_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added quote for {0} saying, {1}.
        /// </summary>
        internal static string response_Added_Quote {
            get {
                return ResourceManager.GetString("response_Added_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted quote {0}.
        /// </summary>
        internal static string response_Deleted_Quote {
            get {
                return ResourceManager.GetString("response_Deleted_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Rolled:
        ///{1}
        ///Total: {2}.
        /// </summary>
        internal static string response_Dice_Roll {
            get {
                return ResourceManager.GetString("response_Dice_Roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disbott C# Edition, Dev Version -- {0}.
        /// </summary>
        internal static string response_Info_Dev {
            get {
                return ResourceManager.GetString("response_Info_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disbott C# Edition, Version 3.0.0 -- {0}.
        /// </summary>
        internal static string response_Info_Live {
            get {
                return ResourceManager.GetString("response_Info_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have been killed, brb.
        /// </summary>
        internal static string response_Killed {
            get {
                return ResourceManager.GetString("response_Killed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have now linked {0} to your Discord Account.
        /// </summary>
        internal static string response_Linked_LolAccount {
            get {
                return ResourceManager.GetString("response_Linked_LolAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pong.
        /// </summary>
        internal static string response_Pong {
            get {
                return ResourceManager.GetString("response_Pong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} said {1}.
        /// </summary>
        internal static string response_Random_Quote {
            get {
                return ResourceManager.GetString("response_Random_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has posted {1} messages.
        /// </summary>
        internal static string response_Total_Messages {
            get {
                return ResourceManager.GetString("response_Total_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string response_Twitter_User {
            get {
                return ResourceManager.GetString("response_Twitter_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/uchuuio/disbott/.
        /// </summary>
        internal static string url_Disbott {
            get {
                return ResourceManager.GetString("url_Disbott", resourceCulture);
            }
        }
    }
}
